import ProjectDescription

let workspace = Workspace(
  name: "Nims",
  projects: [.relativeToRoot(".")],
  schemes: [],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: .none,
    renderMarkdownReadme: false
  )
)
