static vimoption_T options[] = {
  [0]={
    .fullname="aleph",
    .shortname="al",
    .flags=P_NUM|P_CURSWANT,
    .var=(char_u *)&p_aleph,
    .indir=PV_NONE,
    .def_val=(char *) 224L,
  },
  [1]={
    .fullname="arabic",
    .shortname="arab",
    .flags=P_BOOL|P_CURSWANT,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_ARAB),
    .def_val=(char *) false,
  },
  [2]={
    .fullname="arabicshape",
    .shortname="arshape",
    .flags=P_BOOL|P_RALL|P_UI_OPTION,
    .var=(char_u *)&p_arshape,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [3]={
    .fullname="allowrevins",
    .shortname="ari",
    .flags=P_BOOL,
    .var=(char_u *)&p_ari,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [4]={
    .fullname="ambiwidth",
    .shortname="ambw",
    .flags=P_STRING|P_RALL|P_UI_OPTION,
    .var=(char_u *)&p_ambw,
    .indir=PV_NONE,
    .def_val=(char *) "single",
  },
  [5]={
    .fullname="autochdir",
    .shortname="acd",
    .flags=P_BOOL,
    .var=(char_u *)&p_acd,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [6]={
    .fullname="autoindent",
    .shortname="ai",
    .flags=P_BOOL,
    .var=(char_u *)&p_ai,
    .indir=OPT_BUF(BV_AI),
    .def_val=(char *) true,
  },
  [7]={
    .fullname="autoread",
    .shortname="ar",
    .flags=P_BOOL,
    .var=(char_u *)&p_ar,
    .indir=OPT_BOTH(OPT_BUF(BV_AR)),
    .def_val=(char *) true,
  },
  [8]={
    .fullname="autowrite",
    .shortname="aw",
    .flags=P_BOOL,
    .var=(char_u *)&p_aw,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [9]={
    .fullname="autowriteall",
    .shortname="awa",
    .flags=P_BOOL,
    .var=(char_u *)&p_awa,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [10]={
    .fullname="background",
    .shortname="bg",
    .flags=P_STRING,
    .var=(char_u *)&p_bg,
    .indir=PV_NONE,
    .def_val=(char *) "dark",
  },
  [11]={
    .fullname="backspace",
    .shortname="bs",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_bs,
    .indir=PV_NONE,
    .def_val=(char *) "indent,eol,start",
  },
  [12]={
    .fullname="backup",
    .shortname="bk",
    .flags=P_BOOL,
    .var=(char_u *)&p_bk,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [13]={
    .fullname="backupcopy",
    .shortname="bkc",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_bkc,
    .indir=OPT_BOTH(OPT_BUF(BV_BKC)),
#if defined(UNIX)
    .def_val=(char *) "auto",
#else
    .def_val=(char *) "auto",
#endif
  },
  [14]={
    .fullname="backupdir",
    .shortname="bdir",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NO_DEF_EXP|P_SECURE|P_NODUP,
    .var=(char_u *)&p_bdir,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [15]={
    .fullname="backupext",
    .shortname="bex",
    .flags=P_STRING|P_NFNAME,
    .var=(char_u *)&p_bex,
    .indir=PV_NONE,
    .def_val=(char *) "~",
  },
  [16]={
    .fullname="backupskip",
    .shortname="bsk",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_bsk,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [17]={
    .fullname="belloff",
    .shortname="bo",
    .flags=P_STRING|P_COMMA|P_NODUP,
    .var=(char_u *)&p_bo,
    .indir=PV_NONE,
    .def_val=(char *) "all",
  },
  [18]={
    .fullname="binary",
    .shortname="bin",
    .flags=P_BOOL|P_RSTAT,
    .var=(char_u *)&p_bin,
    .indir=OPT_BUF(BV_BIN),
    .def_val=(char *) false,
  },
  [19]={
    .fullname="bomb",
    .flags=P_BOOL|P_RSTAT|P_NO_MKRC,
    .var=(char_u *)&p_bomb,
    .indir=OPT_BUF(BV_BOMB),
    .def_val=(char *) false,
  },
  [20]={
    .fullname="breakat",
    .shortname="brk",
    .flags=P_STRING|P_FLAGLIST|P_RALL,
    .var=(char_u *)&p_breakat,
    .indir=PV_NONE,
    .def_val=(char *) " \t!@*-+;:,./?",
  },
  [21]={
    .fullname="breakindent",
    .shortname="bri",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_BRI),
    .def_val=(char *) false,
  },
  [22]={
    .fullname="breakindentopt",
    .shortname="briopt",
    .flags=P_STRING|P_ONECOMMA|P_RBUF|P_ALLOCED|P_NODUP,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_BRIOPT),
    .def_val=(char *) "",
  },
  [23]={
    .fullname="browsedir",
    .shortname="bsdir",
    .flags=P_STRING,
    .indir=PV_NONE,
  },
  [24]={
    .fullname="bufhidden",
    .shortname="bh",
    .flags=P_STRING|P_ALLOCED|P_NOGLOB,
    .var=(char_u *)&p_bh,
    .indir=OPT_BUF(BV_BH),
    .def_val=(char *) "",
  },
  [25]={
    .fullname="buflisted",
    .shortname="bl",
    .flags=P_BOOL|P_NOGLOB,
    .var=(char_u *)&p_bl,
    .indir=OPT_BUF(BV_BL),
    .def_val=(char *) 1L,
  },
  [26]={
    .fullname="buftype",
    .shortname="bt",
    .flags=P_STRING|P_ALLOCED|P_NOGLOB,
    .var=(char_u *)&p_bt,
    .indir=OPT_BUF(BV_BT),
    .def_val=(char *) "",
  },
  [27]={
    .fullname="casemap",
    .shortname="cmp",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_cmp,
    .indir=PV_NONE,
    .def_val=(char *) "internal,keepascii",
  },
  [28]={
    .fullname="cdhome",
    .shortname="cdh",
    .flags=P_BOOL|P_SECURE,
    .var=(char_u *)&p_cdh,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [29]={
    .fullname="cdpath",
    .shortname="cd",
    .flags=P_STRING|P_COMMA|P_EXPAND|P_SECURE|P_NODUP,
    .var=(char_u *)&p_cdpath,
    .indir=PV_NONE,
    .def_val=(char *) ",,",
  },
  [30]={
    .fullname="cedit",
    .flags=P_STRING,
    .var=(char_u *)&p_cedit,
    .indir=PV_NONE,
    .def_val=(char *) CTRL_F_STR,
  },
  [31]={
    .fullname="channel",
    .flags=P_NUM|P_NODEFAULT|P_NO_MKRC,
    .var=(char_u *)&p_channel,
    .indir=OPT_BUF(BV_CHANNEL),
    .def_val=(char *) 0L,
  },
  [32]={
    .fullname="charconvert",
    .shortname="ccv",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_ccv,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [33]={
    .fullname="cindent",
    .shortname="cin",
    .flags=P_BOOL,
    .var=(char_u *)&p_cin,
    .indir=OPT_BUF(BV_CIN),
    .def_val=(char *) false,
  },
  [34]={
    .fullname="cinkeys",
    .shortname="cink",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_cink,
    .indir=OPT_BUF(BV_CINK),
    .def_val=(char *) "0{,0},0),0],:,0#,!^F,o,O,e",
  },
  [35]={
    .fullname="cinoptions",
    .shortname="cino",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_cino,
    .indir=OPT_BUF(BV_CINO),
    .def_val=(char *) "",
  },
  [36]={
    .fullname="cinwords",
    .shortname="cinw",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_cinw,
    .indir=OPT_BUF(BV_CINW),
    .def_val=(char *) "if,else,while,do,for,switch",
  },
  [37]={
    .fullname="cinscopedecls",
    .shortname="cinsd",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_cinsd,
    .indir=OPT_BUF(BV_CINSD),
    .def_val=(char *) "public,protected,private",
  },
  [38]={
    .fullname="clipboard",
    .shortname="cb",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_cb,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [39]={
    .fullname="cmdheight",
    .shortname="ch",
    .flags=P_NUM|P_RALL,
    .var=(char_u *)&p_ch,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [40]={
    .fullname="cmdwinheight",
    .shortname="cwh",
    .flags=P_NUM,
    .var=(char_u *)&p_cwh,
    .indir=PV_NONE,
    .def_val=(char *) 7L,
  },
  [41]={
    .fullname="colorcolumn",
    .shortname="cc",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_NODUP,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_CC),
    .def_val=(char *) "",
  },
  [42]={
    .fullname="columns",
    .shortname="co",
    .flags=P_NUM|P_NO_MKRC,
    .var=(char_u *)&p_columns,
    .indir=PV_NONE,
    .def_val=(char *) DFLT_COLS,
  },
  [43]={
    .fullname="comments",
    .shortname="com",
    .flags=P_STRING|P_ONECOMMA|P_CURSWANT|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_com,
    .indir=OPT_BUF(BV_COM),
    .def_val=(char *) "s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-",
  },
  [44]={
    .fullname="commentstring",
    .shortname="cms",
    .flags=P_STRING|P_CURSWANT|P_ALLOCED,
    .var=(char_u *)&p_cms,
    .indir=OPT_BUF(BV_CMS),
    .def_val=(char *) "/*%s*/",
  },
  [45]={
    .fullname="compatible",
    .shortname="cp",
    .flags=P_BOOL,
    .var=(char_u *)&p_force_off,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [46]={
    .fullname="complete",
    .shortname="cpt",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_cpt,
    .indir=OPT_BUF(BV_CPT),
    .def_val=(char *) ".,w,b,u,t",
  },
  [47]={
    .fullname="concealcursor",
    .shortname="cocu",
    .flags=P_STRING|P_RWIN|P_ALLOCED,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_COCU),
    .def_val=(char *) "",
  },
  [48]={
    .fullname="conceallevel",
    .shortname="cole",
    .flags=P_NUM|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_COLE),
    .def_val=(char *) 0L,
  },
  [49]={
    .fullname="completefunc",
    .shortname="cfu",
    .flags=P_STRING|P_ALLOCED|P_SECURE|P_FUNC,
    .var=(char_u *)&p_cfu,
    .indir=OPT_BUF(BV_CFU),
    .def_val=(char *) "",
  },
  [50]={
    .fullname="completeopt",
    .shortname="cot",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_cot,
    .indir=PV_NONE,
    .def_val=(char *) "menu,preview",
  },
  [51]={
    .fullname="completeslash",
    .shortname="csl",
    .flags=P_STRING,
#if defined(BACKSLASH_IN_FILENAME)
    .var=(char_u *)&p_csl,
    .indir=OPT_BUF(BV_CSL),
#else
    .var=NULL,
    .indir=PV_NONE,
#endif
    .def_val=(char *) "",
  },
  [52]={
    .fullname="confirm",
    .shortname="cf",
    .flags=P_BOOL,
    .var=(char_u *)&p_confirm,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [53]={
    .fullname="copyindent",
    .shortname="ci",
    .flags=P_BOOL,
    .var=(char_u *)&p_ci,
    .indir=OPT_BUF(BV_CI),
    .def_val=(char *) false,
  },
  [54]={
    .fullname="cpoptions",
    .shortname="cpo",
    .flags=P_STRING|P_FLAGLIST|P_RALL,
    .var=(char_u *)&p_cpo,
    .indir=PV_NONE,
    .def_val=(char *) CPO_VIM,
  },
  [55]={
    .fullname="cursorbind",
    .shortname="crb",
    .flags=P_BOOL,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_CRBIND),
    .def_val=(char *) false,
  },
  [56]={
    .fullname="cursorcolumn",
    .shortname="cuc",
    .flags=P_BOOL|P_RWINONLY,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_CUC),
    .def_val=(char *) false,
  },
  [57]={
    .fullname="cursorline",
    .shortname="cul",
    .flags=P_BOOL|P_RWINONLY,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_CUL),
    .def_val=(char *) false,
  },
  [58]={
    .fullname="cursorlineopt",
    .shortname="culopt",
    .flags=P_STRING|P_ONECOMMA|P_RWINONLY|P_NODUP,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_CULOPT),
    .def_val=(char *) "both",
  },
  [59]={
    .fullname="debug",
    .flags=P_STRING,
    .var=(char_u *)&p_debug,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [60]={
    .fullname="define",
    .shortname="def",
    .flags=P_STRING|P_CURSWANT|P_ALLOCED,
    .var=(char_u *)&p_def,
    .indir=OPT_BOTH(OPT_BUF(BV_DEF)),
    .def_val=(char *) "^\\s*#\\s*define",
  },
  [61]={
    .fullname="delcombine",
    .shortname="deco",
    .flags=P_BOOL,
    .var=(char_u *)&p_deco,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [62]={
    .fullname="dictionary",
    .shortname="dict",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NDNAME|P_NODUP,
    .var=(char_u *)&p_dict,
    .indir=OPT_BOTH(OPT_BUF(BV_DICT)),
    .def_val=(char *) "",
  },
  [63]={
    .fullname="diff",
    .flags=P_BOOL|P_RWIN|P_NOGLOB,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_DIFF),
    .def_val=(char *) false,
  },
  [64]={
    .fullname="diffexpr",
    .shortname="dex",
    .flags=P_STRING|P_CURSWANT|P_SECURE,
    .var=(char_u *)&p_dex,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [65]={
    .fullname="diffopt",
    .shortname="dip",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_dip,
    .indir=PV_NONE,
    .def_val=(char *) "internal,filler,closeoff",
  },
  [66]={
    .fullname="digraph",
    .shortname="dg",
    .flags=P_BOOL,
    .var=(char_u *)&p_dg,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [67]={
    .fullname="directory",
    .shortname="dir",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NO_DEF_EXP|P_SECURE|P_NODUP,
    .var=(char_u *)&p_dir,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [68]={
    .fullname="display",
    .shortname="dy",
    .flags=P_STRING|P_ONECOMMA|P_RALL|P_NODUP,
    .var=(char_u *)&p_dy,
    .indir=PV_NONE,
    .def_val=(char *) "lastline",
  },
  [69]={
    .fullname="eadirection",
    .shortname="ead",
    .flags=P_STRING,
    .var=(char_u *)&p_ead,
    .indir=PV_NONE,
    .def_val=(char *) "both",
  },
  [70]={
    .fullname="edcompatible",
    .shortname="ed",
    .flags=P_BOOL,
    .var=(char_u *)&p_force_off,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [71]={
    .fullname="emoji",
    .shortname="emo",
    .flags=P_BOOL|P_RALL|P_UI_OPTION,
    .var=(char_u *)&p_emoji,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [72]={
    .fullname="encoding",
    .shortname="enc",
    .flags=P_STRING|P_NO_ML,
    .var=(char_u *)&p_enc,
    .indir=PV_NONE,
    .def_val=(char *) ENC_DFLT,
  },
  [73]={
    .fullname="endoffile",
    .shortname="eof",
    .flags=P_BOOL|P_RSTAT|P_NO_MKRC,
    .var=(char_u *)&p_eof,
    .indir=OPT_BUF(BV_EOF),
    .def_val=(char *) true,
  },
  [74]={
    .fullname="endofline",
    .shortname="eol",
    .flags=P_BOOL|P_RSTAT|P_NO_MKRC,
    .var=(char_u *)&p_eol,
    .indir=OPT_BUF(BV_EOL),
    .def_val=(char *) true,
  },
  [75]={
    .fullname="equalalways",
    .shortname="ea",
    .flags=P_BOOL,
    .var=(char_u *)&p_ea,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [76]={
    .fullname="equalprg",
    .shortname="ep",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_ep,
    .indir=OPT_BOTH(OPT_BUF(BV_EP)),
    .def_val=(char *) "",
  },
  [77]={
    .fullname="errorbells",
    .shortname="eb",
    .flags=P_BOOL,
    .var=(char_u *)&p_eb,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [78]={
    .fullname="errorfile",
    .shortname="ef",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_ef,
    .indir=PV_NONE,
    .def_val=(char *) DFLT_ERRORFILE,
  },
  [79]={
    .fullname="errorformat",
    .shortname="efm",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_efm,
    .indir=OPT_BOTH(OPT_BUF(BV_EFM)),
    .def_val=(char *) DFLT_EFM,
  },
  [80]={
    .fullname="eventignore",
    .shortname="ei",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_ei,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [81]={
    .fullname="expandtab",
    .shortname="et",
    .flags=P_BOOL,
    .var=(char_u *)&p_et,
    .indir=OPT_BUF(BV_ET),
    .def_val=(char *) false,
  },
  [82]={
    .fullname="exrc",
    .shortname="ex",
    .flags=P_BOOL|P_SECURE,
    .var=(char_u *)&p_exrc,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [83]={
    .fullname="fileencoding",
    .shortname="fenc",
    .flags=P_STRING|P_RSTAT|P_RBUF|P_ALLOCED|P_NO_MKRC,
    .var=(char_u *)&p_fenc,
    .indir=OPT_BUF(BV_FENC),
    .def_val=(char *) "",
  },
  [84]={
    .fullname="fileencodings",
    .shortname="fencs",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_fencs,
    .indir=PV_NONE,
    .def_val=(char *) "ucs-bom,utf-8,default,latin1",
  },
  [85]={
    .fullname="fileformat",
    .shortname="ff",
    .flags=P_STRING|P_CURSWANT|P_RSTAT|P_ALLOCED|P_NO_MKRC,
    .var=(char_u *)&p_ff,
    .indir=OPT_BUF(BV_FF),
    .def_val=(char *) DFLT_FF,
  },
  [86]={
    .fullname="fileformats",
    .shortname="ffs",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_ffs,
    .indir=PV_NONE,
    .def_val=(char *) DFLT_FFS_VIM,
  },
  [87]={
    .fullname="fileignorecase",
    .shortname="fic",
    .flags=P_BOOL,
    .var=(char_u *)&p_fic,
    .indir=PV_NONE,
#if defined(CASE_INSENSITIVE_FILENAME)
    .def_val=(char *) true,
#endif
  },
  [88]={
    .fullname="filetype",
    .shortname="ft",
    .flags=P_STRING|P_EXPAND|P_ALLOCED|P_NOGLOB|P_NFNAME,
    .var=(char_u *)&p_ft,
    .indir=OPT_BUF(BV_FT),
    .def_val=(char *) "",
  },
  [89]={
    .fullname="fillchars",
    .shortname="fcs",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_fcs,
    .indir=OPT_BOTH(OPT_WIN(WV_FCS)),
    .def_val=(char *) "",
  },
  [90]={
    .fullname="fixendofline",
    .shortname="fixeol",
    .flags=P_BOOL|P_RSTAT,
    .var=(char_u *)&p_fixeol,
    .indir=OPT_BUF(BV_FIXEOL),
    .def_val=(char *) true,
  },
  [91]={
    .fullname="foldclose",
    .shortname="fcl",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_NODUP,
    .var=(char_u *)&p_fcl,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [92]={
    .fullname="foldcolumn",
    .shortname="fdc",
    .flags=P_STRING|P_RWIN|P_ALLOCED,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDC),
    .def_val=(char *) "0",
  },
  [93]={
    .fullname="foldenable",
    .shortname="fen",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FEN),
    .def_val=(char *) true,
  },
  [94]={
    .fullname="foldexpr",
    .shortname="fde",
    .flags=P_STRING|P_RWIN|P_ALLOCED|P_MLE,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDE),
    .def_val=(char *) "0",
  },
  [95]={
    .fullname="foldignore",
    .shortname="fdi",
    .flags=P_STRING|P_RWIN|P_ALLOCED,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDI),
    .def_val=(char *) "#",
  },
  [96]={
    .fullname="foldlevel",
    .shortname="fdl",
    .flags=P_NUM|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDL),
    .def_val=(char *) 0L,
  },
  [97]={
    .fullname="foldlevelstart",
    .shortname="fdls",
    .flags=P_NUM|P_CURSWANT,
    .var=(char_u *)&p_fdls,
    .indir=PV_NONE,
    .def_val=(char *) -1L,
  },
  [98]={
    .fullname="foldmarker",
    .shortname="fmr",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_ALLOCED|P_NODUP,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FMR),
    .def_val=(char *) "{{{,}}}",
  },
  [99]={
    .fullname="foldmethod",
    .shortname="fdm",
    .flags=P_STRING|P_RWIN|P_ALLOCED,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDM),
    .def_val=(char *) "manual",
  },
  [100]={
    .fullname="foldminlines",
    .shortname="fml",
    .flags=P_NUM|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FML),
    .def_val=(char *) 1L,
  },
  [101]={
    .fullname="foldnestmax",
    .shortname="fdn",
    .flags=P_NUM|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDN),
    .def_val=(char *) 20L,
  },
  [102]={
    .fullname="foldopen",
    .shortname="fdo",
    .flags=P_STRING|P_ONECOMMA|P_CURSWANT|P_NODUP,
    .var=(char_u *)&p_fdo,
    .indir=PV_NONE,
    .def_val=(char *) "block,hor,mark,percent,quickfix,search,tag,undo",
  },
  [103]={
    .fullname="foldtext",
    .shortname="fdt",
    .flags=P_STRING|P_RWIN|P_ALLOCED|P_MLE,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_FDT),
    .def_val=(char *) "foldtext()",
  },
  [104]={
    .fullname="formatexpr",
    .shortname="fex",
    .flags=P_STRING|P_ALLOCED|P_MLE,
    .var=(char_u *)&p_fex,
    .indir=OPT_BUF(BV_FEX),
    .def_val=(char *) "",
  },
  [105]={
    .fullname="formatoptions",
    .shortname="fo",
    .flags=P_STRING|P_FLAGLIST|P_ALLOCED,
    .var=(char_u *)&p_fo,
    .indir=OPT_BUF(BV_FO),
    .def_val=(char *) DFLT_FO_VIM,
  },
  [106]={
    .fullname="formatlistpat",
    .shortname="flp",
    .flags=P_STRING|P_ALLOCED,
    .var=(char_u *)&p_flp,
    .indir=OPT_BUF(BV_FLP),
    .def_val=(char *) "^\\s*\\d\\+[\\]:.)}\\t ]\\s*",
  },
  [107]={
    .fullname="formatprg",
    .shortname="fp",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_fp,
    .indir=OPT_BOTH(OPT_BUF(BV_FP)),
    .def_val=(char *) "",
  },
  [108]={
    .fullname="fsync",
    .shortname="fs",
    .flags=P_BOOL|P_SECURE,
    .var=(char_u *)&p_fs,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [109]={
    .fullname="gdefault",
    .shortname="gd",
    .flags=P_BOOL,
    .var=(char_u *)&p_gd,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [110]={
    .fullname="grepformat",
    .shortname="gfm",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_gefm,
    .indir=PV_NONE,
    .def_val=(char *) DFLT_GREPFORMAT,
  },
  [111]={
    .fullname="grepprg",
    .shortname="gp",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_gp,
    .indir=OPT_BOTH(OPT_BUF(BV_GP)),
#if defined(MSWIN)
    .def_val=(char *) "findstr /n $* nul",
#else
    .def_val=(char *) "grep -n $* /dev/null",
#endif
  },
  [112]={
    .fullname="guicursor",
    .shortname="gcr",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_guicursor,
    .indir=PV_NONE,
    .def_val=(char *) "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20",
  },
  [113]={
    .fullname="guifont",
    .shortname="gfn",
    .flags=P_STRING|P_ONECOMMA|P_UI_OPTION|P_NODUP,
    .var=(char_u *)&p_guifont,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [114]={
    .fullname="guifontwide",
    .shortname="gfw",
    .flags=P_STRING|P_ONECOMMA|P_UI_OPTION|P_NODUP,
    .var=(char_u *)&p_guifontwide,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [115]={
    .fullname="guioptions",
    .shortname="go",
    .flags=P_STRING|P_FLAGLIST,
    .indir=PV_NONE,
  },
  [116]={
    .fullname="guitablabel",
    .shortname="gtl",
    .flags=P_STRING|P_RWIN|P_MLE,
    .indir=PV_NONE,
  },
  [117]={
    .fullname="guitabtooltip",
    .shortname="gtt",
    .flags=P_STRING|P_RWIN,
    .indir=PV_NONE,
  },
  [118]={
    .fullname="helpfile",
    .shortname="hf",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_hf,
    .indir=PV_NONE,
    .def_val=(char *) DFLT_HELPFILE,
  },
  [119]={
    .fullname="helpheight",
    .shortname="hh",
    .flags=P_NUM,
    .var=(char_u *)&p_hh,
    .indir=PV_NONE,
    .def_val=(char *) 20L,
  },
  [120]={
    .fullname="helplang",
    .shortname="hlg",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_hlg,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [121]={
    .fullname="hidden",
    .shortname="hid",
    .flags=P_BOOL,
    .var=(char_u *)&p_hid,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [122]={
    .fullname="highlight",
    .shortname="hl",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_hl,
    .indir=PV_NONE,
    .def_val=(char *) HIGHLIGHT_INIT,
  },
  [123]={
    .fullname="history",
    .shortname="hi",
    .flags=P_NUM,
    .var=(char_u *)&p_hi,
    .indir=PV_NONE,
    .def_val=(char *) 10000L,
  },
  [124]={
    .fullname="hkmap",
    .shortname="hk",
    .flags=P_BOOL,
    .var=(char_u *)&p_hkmap,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [125]={
    .fullname="hkmapp",
    .shortname="hkp",
    .flags=P_BOOL,
    .var=(char_u *)&p_hkmapp,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [126]={
    .fullname="hlsearch",
    .shortname="hls",
    .flags=P_BOOL|P_RALL,
    .var=(char_u *)&p_hls,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [127]={
    .fullname="icon",
    .flags=P_BOOL,
    .var=(char_u *)&p_icon,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [128]={
    .fullname="iconstring",
    .flags=P_STRING|P_MLE,
    .var=(char_u *)&p_iconstring,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [129]={
    .fullname="ignorecase",
    .shortname="ic",
    .flags=P_BOOL,
    .var=(char_u *)&p_ic,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [130]={
    .fullname="imcmdline",
    .shortname="imc",
    .flags=P_BOOL,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [131]={
    .fullname="imdisable",
    .shortname="imd",
    .flags=P_BOOL,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [132]={
    .fullname="iminsert",
    .shortname="imi",
    .flags=P_NUM,
    .var=(char_u *)&p_iminsert,
    .indir=OPT_BUF(BV_IMI),
    .def_val=(char *) B_IMODE_NONE,
  },
  [133]={
    .fullname="imsearch",
    .shortname="ims",
    .flags=P_NUM,
    .var=(char_u *)&p_imsearch,
    .indir=OPT_BUF(BV_IMS),
    .def_val=(char *) B_IMODE_USE_INSERT,
  },
  [134]={
    .fullname="inccommand",
    .shortname="icm",
    .flags=P_STRING,
    .var=(char_u *)&p_icm,
    .indir=PV_NONE,
    .def_val=(char *) "nosplit",
  },
  [135]={
    .fullname="include",
    .shortname="inc",
    .flags=P_STRING|P_ALLOCED,
    .var=(char_u *)&p_inc,
    .indir=OPT_BOTH(OPT_BUF(BV_INC)),
    .def_val=(char *) "^\\s*#\\s*include",
  },
  [136]={
    .fullname="includeexpr",
    .shortname="inex",
    .flags=P_STRING|P_ALLOCED|P_MLE,
    .var=(char_u *)&p_inex,
    .indir=OPT_BUF(BV_INEX),
    .def_val=(char *) "",
  },
  [137]={
    .fullname="incsearch",
    .shortname="is",
    .flags=P_BOOL,
    .var=(char_u *)&p_is,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [138]={
    .fullname="indentexpr",
    .shortname="inde",
    .flags=P_STRING|P_ALLOCED|P_MLE,
    .var=(char_u *)&p_inde,
    .indir=OPT_BUF(BV_INDE),
    .def_val=(char *) "",
  },
  [139]={
    .fullname="indentkeys",
    .shortname="indk",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_indk,
    .indir=OPT_BUF(BV_INDK),
    .def_val=(char *) "0{,0},0),0],:,0#,!^F,o,O,e",
  },
  [140]={
    .fullname="infercase",
    .shortname="inf",
    .flags=P_BOOL,
    .var=(char_u *)&p_inf,
    .indir=OPT_BUF(BV_INF),
    .def_val=(char *) false,
  },
  [141]={
    .fullname="insertmode",
    .shortname="im",
    .flags=P_BOOL,
    .var=(char_u *)&p_force_off,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [142]={
    .fullname="isfname",
    .shortname="isf",
    .flags=P_STRING|P_COMMA|P_NODUP,
    .var=(char_u *)&p_isf,
    .indir=PV_NONE,
#if defined(BACKSLASH_IN_FILENAME)
    .def_val=(char *) "@,48-57,/,\\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=",
#else
    .def_val=(char *) "@,48-57,/,.,-,_,+,,,#,$,%,~,=",
#endif
  },
  [143]={
    .fullname="isident",
    .shortname="isi",
    .flags=P_STRING|P_COMMA|P_NODUP,
    .var=(char_u *)&p_isi,
    .indir=PV_NONE,
#if defined(MSWIN)
    .def_val=(char *) "@,48-57,_,128-167,224-235",
#else
    .def_val=(char *) "@,48-57,_,192-255",
#endif
  },
  [144]={
    .fullname="iskeyword",
    .shortname="isk",
    .flags=P_STRING|P_COMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_isk,
    .indir=OPT_BUF(BV_ISK),
    .def_val=(char *) "@,48-57,_,192-255",
  },
  [145]={
    .fullname="isprint",
    .shortname="isp",
    .flags=P_STRING|P_COMMA|P_RALL|P_NODUP,
    .var=(char_u *)&p_isp,
    .indir=PV_NONE,
    .def_val=(char *) "@,161-255",
  },
  [146]={
    .fullname="joinspaces",
    .shortname="js",
    .flags=P_BOOL,
    .var=(char_u *)&p_js,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [147]={
    .fullname="jumpoptions",
    .shortname="jop",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_jop,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [148]={
    .fullname="keymap",
    .shortname="kmp",
    .flags=P_STRING|P_RSTAT|P_RBUF|P_ALLOCED|P_NFNAME|P_PRI_MKRC,
    .var=(char_u *)&p_keymap,
    .indir=OPT_BUF(BV_KMAP),
    .def_val=(char *) "",
  },
  [149]={
    .fullname="keymodel",
    .shortname="km",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_km,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [150]={
    .fullname="keywordprg",
    .shortname="kp",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_kp,
    .indir=OPT_BOTH(OPT_BUF(BV_KP)),
    .def_val=(char *) ":Man",
  },
  [151]={
    .fullname="langmap",
    .shortname="lmap",
    .flags=P_STRING|P_ONECOMMA|P_SECURE|P_NODUP,
    .var=(char_u *)&p_langmap,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [152]={
    .fullname="langmenu",
    .shortname="lm",
    .flags=P_STRING|P_NFNAME,
    .var=(char_u *)&p_lm,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [153]={
    .fullname="langnoremap",
    .shortname="lnr",
    .flags=P_BOOL,
    .var=(char_u *)&p_lnr,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [154]={
    .fullname="langremap",
    .shortname="lrm",
    .flags=P_BOOL,
    .var=(char_u *)&p_lrm,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [155]={
    .fullname="laststatus",
    .shortname="ls",
    .flags=P_NUM|P_RALL,
    .var=(char_u *)&p_ls,
    .indir=PV_NONE,
    .def_val=(char *) 2L,
  },
  [156]={
    .fullname="lazyredraw",
    .shortname="lz",
    .flags=P_BOOL,
    .var=(char_u *)&p_lz,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [157]={
    .fullname="linebreak",
    .shortname="lbr",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_LBR),
    .def_val=(char *) false,
  },
  [158]={
    .fullname="lines",
    .flags=P_NUM|P_NO_MKRC,
    .var=(char_u *)&p_lines,
    .indir=PV_NONE,
    .def_val=(char *) DFLT_ROWS,
  },
  [159]={
    .fullname="linespace",
    .shortname="lsp",
    .flags=P_NUM|P_UI_OPTION,
    .var=(char_u *)&p_linespace,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [160]={
    .fullname="lisp",
    .flags=P_BOOL,
    .var=(char_u *)&p_lisp,
    .indir=OPT_BUF(BV_LISP),
    .def_val=(char *) false,
  },
  [161]={
    .fullname="lispoptions",
    .shortname="lop",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_lop,
    .indir=OPT_BUF(BV_LOP),
    .def_val=(char *) "",
  },
  [162]={
    .fullname="lispwords",
    .shortname="lw",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_lispwords,
    .indir=OPT_BOTH(OPT_BUF(BV_LW)),
    .def_val=(char *) LISPWORD_VALUE,
  },
  [163]={
    .fullname="list",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_LIST),
    .def_val=(char *) false,
  },
  [164]={
    .fullname="listchars",
    .shortname="lcs",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_lcs,
    .indir=OPT_BOTH(OPT_WIN(WV_LCS)),
    .def_val=(char *) "tab:> ,trail:-,nbsp:+",
  },
  [165]={
    .fullname="loadplugins",
    .shortname="lpl",
    .flags=P_BOOL,
    .var=(char_u *)&p_lpl,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [166]={
    .fullname="magic",
    .flags=P_BOOL,
    .var=(char_u *)&p_magic,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [167]={
    .fullname="makeef",
    .shortname="mef",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_mef,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [168]={
    .fullname="makeencoding",
    .shortname="menc",
    .flags=P_STRING,
    .var=(char_u *)&p_menc,
    .indir=OPT_BOTH(OPT_BUF(BV_MENC)),
    .def_val=(char *) "",
  },
  [169]={
    .fullname="makeprg",
    .shortname="mp",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_mp,
    .indir=OPT_BOTH(OPT_BUF(BV_MP)),
    .def_val=(char *) "make",
  },
  [170]={
    .fullname="matchpairs",
    .shortname="mps",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_mps,
    .indir=OPT_BUF(BV_MPS),
    .def_val=(char *) "(:),{:},[:]",
  },
  [171]={
    .fullname="matchtime",
    .shortname="mat",
    .flags=P_NUM,
    .var=(char_u *)&p_mat,
    .indir=PV_NONE,
    .def_val=(char *) 5L,
  },
  [172]={
    .fullname="maxcombine",
    .shortname="mco",
    .flags=P_NUM,
    .var=(char_u *)&p_mco,
    .indir=PV_NONE,
    .def_val=(char *) 6L,
  },
  [173]={
    .fullname="maxfuncdepth",
    .shortname="mfd",
    .flags=P_NUM,
    .var=(char_u *)&p_mfd,
    .indir=PV_NONE,
    .def_val=(char *) 100L,
  },
  [174]={
    .fullname="maxmapdepth",
    .shortname="mmd",
    .flags=P_NUM,
    .var=(char_u *)&p_mmd,
    .indir=PV_NONE,
    .def_val=(char *) 1000L,
  },
  [175]={
    .fullname="maxmempattern",
    .shortname="mmp",
    .flags=P_NUM,
    .var=(char_u *)&p_mmp,
    .indir=PV_NONE,
    .def_val=(char *) 1000L,
  },
  [176]={
    .fullname="menuitems",
    .shortname="mis",
    .flags=P_NUM,
    .var=(char_u *)&p_mis,
    .indir=PV_NONE,
    .def_val=(char *) 25L,
  },
  [177]={
    .fullname="mkspellmem",
    .shortname="msm",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_msm,
    .indir=PV_NONE,
    .def_val=(char *) "460000,2000,500",
  },
  [178]={
    .fullname="modeline",
    .shortname="ml",
    .flags=P_BOOL,
    .var=(char_u *)&p_ml,
    .indir=OPT_BUF(BV_ML),
    .def_val=(char *) true,
  },
  [179]={
    .fullname="modelineexpr",
    .shortname="mle",
    .flags=P_BOOL|P_SECURE,
    .var=(char_u *)&p_mle,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [180]={
    .fullname="modelines",
    .shortname="mls",
    .flags=P_NUM,
    .var=(char_u *)&p_mls,
    .indir=PV_NONE,
    .def_val=(char *) 5L,
  },
  [181]={
    .fullname="modifiable",
    .shortname="ma",
    .flags=P_BOOL|P_NOGLOB,
    .var=(char_u *)&p_ma,
    .indir=OPT_BUF(BV_MA),
    .def_val=(char *) true,
  },
  [182]={
    .fullname="modified",
    .shortname="mod",
    .flags=P_BOOL|P_RSTAT|P_NO_MKRC,
    .var=(char_u *)&p_mod,
    .indir=OPT_BUF(BV_MOD),
    .def_val=(char *) false,
  },
  [183]={
    .fullname="more",
    .flags=P_BOOL,
    .var=(char_u *)&p_more,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [184]={
    .fullname="mouse",
    .flags=P_STRING|P_FLAGLIST,
    .var=(char_u *)&p_mouse,
    .indir=PV_NONE,
    .def_val=(char *) "nvi",
  },
  [185]={
    .fullname="mousefocus",
    .shortname="mousef",
    .flags=P_BOOL|P_UI_OPTION,
    .var=(char_u *)&p_mousef,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [186]={
    .fullname="mousehide",
    .shortname="mh",
    .flags=P_BOOL,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [187]={
    .fullname="mousemodel",
    .shortname="mousem",
    .flags=P_STRING,
    .var=(char_u *)&p_mousem,
    .indir=PV_NONE,
    .def_val=(char *) "popup_setpos",
  },
  [188]={
    .fullname="mousemoveevent",
    .shortname="mousemev",
    .flags=P_BOOL|P_UI_OPTION,
    .var=(char_u *)&p_mousemev,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [189]={
    .fullname="mousescroll",
    .flags=P_STRING|P_COMMA,
    .var=(char_u *)&p_mousescroll,
    .indir=PV_NONE,
    .def_val=(char *) "ver:3,hor:6",
  },
  [190]={
    .fullname="mouseshape",
    .shortname="mouses",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .indir=PV_NONE,
  },
  [191]={
    .fullname="mousetime",
    .shortname="mouset",
    .flags=P_NUM,
    .var=(char_u *)&p_mouset,
    .indir=PV_NONE,
    .def_val=(char *) 500L,
  },
  [192]={
    .fullname="nrformats",
    .shortname="nf",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_nf,
    .indir=OPT_BUF(BV_NF),
    .def_val=(char *) "bin,hex",
  },
  [193]={
    .fullname="number",
    .shortname="nu",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_NU),
    .def_val=(char *) false,
  },
  [194]={
    .fullname="numberwidth",
    .shortname="nuw",
    .flags=P_NUM|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_NUW),
    .def_val=(char *) 4L,
  },
  [195]={
    .fullname="omnifunc",
    .shortname="ofu",
    .flags=P_STRING|P_ALLOCED|P_SECURE|P_FUNC,
    .var=(char_u *)&p_ofu,
    .indir=OPT_BUF(BV_OFU),
    .def_val=(char *) "",
  },
  [196]={
    .fullname="opendevice",
    .shortname="odev",
    .flags=P_BOOL,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [197]={
    .fullname="operatorfunc",
    .shortname="opfunc",
    .flags=P_STRING|P_SECURE|P_FUNC,
    .var=(char_u *)&p_opfunc,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [198]={
    .fullname="packpath",
    .shortname="pp",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_SECURE|P_NODUP,
    .var=(char_u *)&p_pp,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [199]={
    .fullname="paragraphs",
    .shortname="para",
    .flags=P_STRING,
    .var=(char_u *)&p_para,
    .indir=PV_NONE,
    .def_val=(char *) "IPLPPPQPP TPHPLIPpLpItpplpipbp",
  },
  [200]={
    .fullname="paste",
    .flags=P_BOOL|P_PRI_MKRC,
    .var=(char_u *)&p_paste,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [201]={
    .fullname="pastetoggle",
    .shortname="pt",
    .flags=P_STRING,
    .var=(char_u *)&p_pt,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [202]={
    .fullname="patchexpr",
    .shortname="pex",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_pex,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [203]={
    .fullname="patchmode",
    .shortname="pm",
    .flags=P_STRING|P_NFNAME,
    .var=(char_u *)&p_pm,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [204]={
    .fullname="path",
    .shortname="pa",
    .flags=P_STRING|P_COMMA|P_EXPAND|P_NODUP,
    .var=(char_u *)&p_path,
    .indir=OPT_BOTH(OPT_BUF(BV_PATH)),
    .def_val=(char *) ".,/usr/include,,",
  },
  [205]={
    .fullname="preserveindent",
    .shortname="pi",
    .flags=P_BOOL,
    .var=(char_u *)&p_pi,
    .indir=OPT_BUF(BV_PI),
    .def_val=(char *) false,
  },
  [206]={
    .fullname="previewheight",
    .shortname="pvh",
    .flags=P_NUM,
    .var=(char_u *)&p_pvh,
    .indir=PV_NONE,
    .def_val=(char *) 12L,
  },
  [207]={
    .fullname="previewwindow",
    .shortname="pvw",
    .flags=P_BOOL|P_RSTAT|P_NOGLOB,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_PVW),
    .def_val=(char *) false,
  },
  [208]={
    .fullname="printdevice",
    .shortname="pdev",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_pdev,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [209]={
    .fullname="printencoding",
    .shortname="penc",
    .flags=P_STRING,
    .var=(char_u *)&p_penc,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [210]={
    .fullname="printexpr",
    .shortname="pexpr",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_pexpr,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [211]={
    .fullname="printfont",
    .shortname="pfn",
    .flags=P_STRING,
    .var=(char_u *)&p_pfn,
    .indir=PV_NONE,
    .def_val=(char *) "courier",
  },
  [212]={
    .fullname="printheader",
    .shortname="pheader",
    .flags=P_STRING,
    .var=(char_u *)&p_header,
    .indir=PV_NONE,
    .def_val=(char *) "%<%f%h%m%=Page %N",
  },
  [213]={
    .fullname="printmbcharset",
    .shortname="pmbcs",
    .flags=P_STRING,
    .var=(char_u *)&p_pmcs,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [214]={
    .fullname="printmbfont",
    .shortname="pmbfn",
    .flags=P_STRING,
    .var=(char_u *)&p_pmfn,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [215]={
    .fullname="printoptions",
    .shortname="popt",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_popt,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [216]={
    .fullname="prompt",
    .flags=P_BOOL,
    .var=(char_u *)&p_force_on,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [217]={
    .fullname="pumblend",
    .shortname="pb",
    .flags=P_NUM|P_UI_OPTION,
    .var=(char_u *)&p_pb,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [218]={
    .fullname="pumheight",
    .shortname="ph",
    .flags=P_NUM,
    .var=(char_u *)&p_ph,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [219]={
    .fullname="pumwidth",
    .shortname="pw",
    .flags=P_NUM,
    .var=(char_u *)&p_pw,
    .indir=PV_NONE,
    .def_val=(char *) 15L,
  },
  [220]={
    .fullname="pyxversion",
    .shortname="pyx",
    .flags=P_NUM|P_SECURE,
    .var=(char_u *)&p_pyx,
    .indir=PV_NONE,
    .def_val=(char *) 3L,
  },
  [221]={
    .fullname="quickfixtextfunc",
    .shortname="qftf",
    .flags=P_STRING|P_SECURE|P_FUNC,
    .var=(char_u *)&p_qftf,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [222]={
    .fullname="quoteescape",
    .shortname="qe",
    .flags=P_STRING|P_ALLOCED,
    .var=(char_u *)&p_qe,
    .indir=OPT_BUF(BV_QE),
    .def_val=(char *) "\\",
  },
  [223]={
    .fullname="readonly",
    .shortname="ro",
    .flags=P_BOOL|P_RSTAT|P_NOGLOB,
    .var=(char_u *)&p_ro,
    .indir=OPT_BUF(BV_RO),
    .def_val=(char *) false,
  },
  [224]={
    .fullname="redrawdebug",
    .shortname="rdb",
    .flags=P_STRING|P_ONECOMMA,
    .var=(char_u *)&p_rdb,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [225]={
    .fullname="redrawtime",
    .shortname="rdt",
    .flags=P_NUM,
    .var=(char_u *)&p_rdt,
    .indir=PV_NONE,
    .def_val=(char *) 2000L,
  },
  [226]={
    .fullname="regexpengine",
    .shortname="re",
    .flags=P_NUM,
    .var=(char_u *)&p_re,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [227]={
    .fullname="relativenumber",
    .shortname="rnu",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_RNU),
    .def_val=(char *) false,
  },
  [228]={
    .fullname="remap",
    .flags=P_BOOL,
    .var=(char_u *)&p_force_on,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [229]={
    .fullname="report",
    .flags=P_NUM,
    .var=(char_u *)&p_report,
    .indir=PV_NONE,
    .def_val=(char *) 2L,
  },
  [230]={
    .fullname="revins",
    .shortname="ri",
    .flags=P_BOOL,
    .var=(char_u *)&p_ri,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [231]={
    .fullname="rightleft",
    .shortname="rl",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_RL),
    .def_val=(char *) false,
  },
  [232]={
    .fullname="rightleftcmd",
    .shortname="rlc",
    .flags=P_STRING|P_RWIN|P_ALLOCED,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_RLC),
    .def_val=(char *) "search",
  },
  [233]={
    .fullname="ruler",
    .shortname="ru",
    .flags=P_BOOL|P_RSTAT,
    .var=(char_u *)&p_ru,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [234]={
    .fullname="rulerformat",
    .shortname="ruf",
    .flags=P_STRING|P_RSTAT|P_ALLOCED|P_MLE,
    .var=(char_u *)&p_ruf,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [235]={
    .fullname="runtimepath",
    .shortname="rtp",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NO_DEF_EXP|P_SECURE|P_NODUP,
    .var=(char_u *)&p_rtp,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [236]={
    .fullname="scroll",
    .shortname="scr",
    .flags=P_NUM|P_NO_MKRC,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_SCROLL),
    .def_val=(char *) 0L,
  },
  [237]={
    .fullname="scrollback",
    .shortname="scbk",
    .flags=P_NUM|P_RBUF,
    .var=(char_u *)&p_scbk,
    .indir=OPT_BUF(BV_SCBK),
    .def_val=(char *) -1L,
  },
  [238]={
    .fullname="scrollbind",
    .shortname="scb",
    .flags=P_BOOL,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_SCBIND),
    .def_val=(char *) false,
  },
  [239]={
    .fullname="scrolljump",
    .shortname="sj",
    .flags=P_NUM,
    .var=(char_u *)&p_sj,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [240]={
    .fullname="scrolloff",
    .shortname="so",
    .flags=P_NUM,
    .var=(char_u *)&p_so,
    .indir=OPT_BOTH(OPT_WIN(WV_SO)),
    .def_val=(char *) 0L,
  },
  [241]={
    .fullname="scrollopt",
    .shortname="sbo",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_sbo,
    .indir=PV_NONE,
    .def_val=(char *) "ver,jump",
  },
  [242]={
    .fullname="sections",
    .shortname="sect",
    .flags=P_STRING,
    .var=(char_u *)&p_sections,
    .indir=PV_NONE,
    .def_val=(char *) "SHNHH HUnhsh",
  },
  [243]={
    .fullname="secure",
    .flags=P_BOOL|P_SECURE,
    .var=(char_u *)&p_secure,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [244]={
    .fullname="selection",
    .shortname="sel",
    .flags=P_STRING,
    .var=(char_u *)&p_sel,
    .indir=PV_NONE,
    .def_val=(char *) "inclusive",
  },
  [245]={
    .fullname="selectmode",
    .shortname="slm",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_slm,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [246]={
    .fullname="sessionoptions",
    .shortname="ssop",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_ssop,
    .indir=PV_NONE,
    .def_val=(char *) "blank,buffers,curdir,folds,help,tabpages,winsize,terminal",
  },
  [247]={
    .fullname="shada",
    .shortname="sd",
    .flags=P_STRING|P_ONECOMMA|P_SECURE|P_NODUP,
    .var=(char_u *)&p_shada,
    .indir=PV_NONE,
    .def_val=(char *) "!,'100,<50,s10,h",
  },
  [248]={
    .fullname="shadafile",
    .shortname="sdf",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_SECURE|P_NODUP,
    .var=(char_u *)&p_shadafile,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [249]={
    .fullname="shell",
    .shortname="sh",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_sh,
    .indir=PV_NONE,
#if defined(MSWIN)
    .def_val=(char *) "cmd.exe",
#else
    .def_val=(char *) "sh",
#endif
  },
  [250]={
    .fullname="shellcmdflag",
    .shortname="shcf",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_shcf,
    .indir=PV_NONE,
#if defined(MSWIN)
    .def_val=(char *) "/s /c",
#else
    .def_val=(char *) "-c",
#endif
  },
  [251]={
    .fullname="shellpipe",
    .shortname="sp",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_sp,
    .indir=PV_NONE,
#if defined(MSWIN)
    .def_val=(char *) ">%s 2>&1",
#else
    .def_val=(char *) "| tee",
#endif
  },
  [252]={
    .fullname="shellquote",
    .shortname="shq",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_shq,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [253]={
    .fullname="shellredir",
    .shortname="srr",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_srr,
    .indir=PV_NONE,
#if defined(MSWIN)
    .def_val=(char *) ">%s 2>&1",
#else
    .def_val=(char *) ">",
#endif
  },
  [254]={
    .fullname="shellslash",
    .shortname="ssl",
    .flags=P_BOOL,
#if defined(BACKSLASH_IN_FILENAME)
    .var=(char_u *)&p_ssl,
    .indir=PV_NONE,
#else
    .var=NULL,
    .indir=PV_NONE,
#endif
    .def_val=(char *) false,
  },
  [255]={
    .fullname="shelltemp",
    .shortname="stmp",
    .flags=P_BOOL,
    .var=(char_u *)&p_stmp,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [256]={
    .fullname="shellxquote",
    .shortname="sxq",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_sxq,
    .indir=PV_NONE,
#if defined(MSWIN)
    .def_val=(char *) "\"",
#else
    .def_val=(char *) "",
#endif
  },
  [257]={
    .fullname="shellxescape",
    .shortname="sxe",
    .flags=P_STRING|P_SECURE,
    .var=(char_u *)&p_sxe,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [258]={
    .fullname="shiftround",
    .shortname="sr",
    .flags=P_BOOL,
    .var=(char_u *)&p_sr,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [259]={
    .fullname="shiftwidth",
    .shortname="sw",
    .flags=P_NUM,
    .var=(char_u *)&p_sw,
    .indir=OPT_BUF(BV_SW),
    .def_val=(char *) 8L,
  },
  [260]={
    .fullname="shortmess",
    .shortname="shm",
    .flags=P_STRING|P_FLAGLIST,
    .var=(char_u *)&p_shm,
    .indir=PV_NONE,
    .def_val=(char *) "filnxtToOF",
  },
  [261]={
    .fullname="showbreak",
    .shortname="sbr",
    .flags=P_STRING|P_RALL,
    .var=(char_u *)&p_sbr,
    .indir=OPT_BOTH(OPT_WIN(WV_SBR)),
    .def_val=(char *) "",
  },
  [262]={
    .fullname="showcmd",
    .shortname="sc",
    .flags=P_BOOL,
    .var=(char_u *)&p_sc,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [263]={
    .fullname="showfulltag",
    .shortname="sft",
    .flags=P_BOOL,
    .var=(char_u *)&p_sft,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [264]={
    .fullname="showmatch",
    .shortname="sm",
    .flags=P_BOOL,
    .var=(char_u *)&p_sm,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [265]={
    .fullname="showmode",
    .shortname="smd",
    .flags=P_BOOL,
    .var=(char_u *)&p_smd,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [266]={
    .fullname="showtabline",
    .shortname="stal",
    .flags=P_NUM|P_RALL|P_UI_OPTION,
    .var=(char_u *)&p_stal,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [267]={
    .fullname="sidescroll",
    .shortname="ss",
    .flags=P_NUM,
    .var=(char_u *)&p_ss,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [268]={
    .fullname="sidescrolloff",
    .shortname="siso",
    .flags=P_NUM,
    .var=(char_u *)&p_siso,
    .indir=OPT_BOTH(OPT_WIN(WV_SISO)),
    .def_val=(char *) 0L,
  },
  [269]={
    .fullname="signcolumn",
    .shortname="scl",
    .flags=P_STRING|P_RWIN|P_ALLOCED,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_SCL),
    .def_val=(char *) "auto",
  },
  [270]={
    .fullname="smartcase",
    .shortname="scs",
    .flags=P_BOOL,
    .var=(char_u *)&p_scs,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [271]={
    .fullname="smartindent",
    .shortname="si",
    .flags=P_BOOL,
    .var=(char_u *)&p_si,
    .indir=OPT_BUF(BV_SI),
    .def_val=(char *) false,
  },
  [272]={
    .fullname="smarttab",
    .shortname="sta",
    .flags=P_BOOL,
    .var=(char_u *)&p_sta,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [273]={
    .fullname="softtabstop",
    .shortname="sts",
    .flags=P_NUM,
    .var=(char_u *)&p_sts,
    .indir=OPT_BUF(BV_STS),
    .def_val=(char *) 0L,
  },
  [274]={
    .fullname="spell",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_SPELL),
    .def_val=(char *) false,
  },
  [275]={
    .fullname="spellcapcheck",
    .shortname="spc",
    .flags=P_STRING|P_RBUF|P_ALLOCED,
    .var=(char_u *)&p_spc,
    .indir=OPT_BUF(BV_SPC),
    .def_val=(char *) "[.?!]\\_[\\])'\"\t ]\\+",
  },
  [276]={
    .fullname="spellfile",
    .shortname="spf",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_ALLOCED|P_SECURE|P_NODUP,
    .var=(char_u *)&p_spf,
    .indir=OPT_BUF(BV_SPF),
    .def_val=(char *) "",
  },
  [277]={
    .fullname="spelllang",
    .shortname="spl",
    .flags=P_STRING|P_ONECOMMA|P_RBUF|P_EXPAND|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_spl,
    .indir=OPT_BUF(BV_SPL),
    .def_val=(char *) "en",
  },
  [278]={
    .fullname="spellsuggest",
    .shortname="sps",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_SECURE|P_NODUP,
    .var=(char_u *)&p_sps,
    .indir=PV_NONE,
    .def_val=(char *) "best",
  },
  [279]={
    .fullname="spelloptions",
    .shortname="spo",
    .flags=P_STRING|P_ONECOMMA|P_RBUF|P_EXPAND|P_SECURE|P_NODUP,
    .var=(char_u *)&p_spo,
    .indir=OPT_BUF(BV_SPO),
    .def_val=(char *) "",
  },
  [280]={
    .fullname="splitbelow",
    .shortname="sb",
    .flags=P_BOOL,
    .var=(char_u *)&p_sb,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [281]={
    .fullname="splitkeep",
    .shortname="spk",
    .flags=P_STRING,
    .var=(char_u *)&p_spk,
    .indir=PV_NONE,
    .def_val=(char *) "cursor",
  },
  [282]={
    .fullname="splitright",
    .shortname="spr",
    .flags=P_BOOL,
    .var=(char_u *)&p_spr,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [283]={
    .fullname="startofline",
    .shortname="sol",
    .flags=P_BOOL,
    .var=(char_u *)&p_sol,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [284]={
    .fullname="statusline",
    .shortname="stl",
    .flags=P_STRING|P_RSTAT|P_ALLOCED|P_MLE,
    .var=(char_u *)&p_stl,
    .indir=OPT_BOTH(OPT_WIN(WV_STL)),
    .def_val=(char *) "",
  },
  [285]={
    .fullname="suffixes",
    .shortname="su",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_su,
    .indir=PV_NONE,
    .def_val=(char *) ".bak,~,.o,.h,.info,.swp,.obj",
  },
  [286]={
    .fullname="suffixesadd",
    .shortname="sua",
    .flags=P_STRING|P_ONECOMMA|P_ALLOCED|P_NODUP,
    .var=(char_u *)&p_sua,
    .indir=OPT_BUF(BV_SUA),
    .def_val=(char *) "",
  },
  [287]={
    .fullname="swapfile",
    .shortname="swf",
    .flags=P_BOOL|P_RSTAT,
    .var=(char_u *)&p_swf,
    .indir=OPT_BUF(BV_SWF),
    .def_val=(char *) true,
  },
  [288]={
    .fullname="switchbuf",
    .shortname="swb",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_swb,
    .indir=PV_NONE,
    .def_val=(char *) "uselast",
  },
  [289]={
    .fullname="synmaxcol",
    .shortname="smc",
    .flags=P_NUM|P_RBUF,
    .var=(char_u *)&p_smc,
    .indir=OPT_BUF(BV_SMC),
    .def_val=(char *) 3000L,
  },
  [290]={
    .fullname="syntax",
    .shortname="syn",
    .flags=P_STRING|P_ALLOCED|P_NOGLOB|P_NFNAME,
    .var=(char_u *)&p_syn,
    .indir=OPT_BUF(BV_SYN),
    .def_val=(char *) "",
  },
  [291]={
    .fullname="tagfunc",
    .shortname="tfu",
    .flags=P_STRING|P_SECURE|P_FUNC,
    .var=(char_u *)&p_tfu,
    .indir=OPT_BUF(BV_TFU),
    .def_val=(char *) "",
  },
  [292]={
    .fullname="tabline",
    .shortname="tal",
    .flags=P_STRING|P_RTABL|P_MLE,
    .var=(char_u *)&p_tal,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [293]={
    .fullname="tabpagemax",
    .shortname="tpm",
    .flags=P_NUM,
    .var=(char_u *)&p_tpm,
    .indir=PV_NONE,
    .def_val=(char *) 50L,
  },
  [294]={
    .fullname="tabstop",
    .shortname="ts",
    .flags=P_NUM|P_RBUF,
    .var=(char_u *)&p_ts,
    .indir=OPT_BUF(BV_TS),
    .def_val=(char *) 8L,
  },
  [295]={
    .fullname="tagbsearch",
    .shortname="tbs",
    .flags=P_BOOL,
    .var=(char_u *)&p_tbs,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [296]={
    .fullname="tagcase",
    .shortname="tc",
    .flags=P_STRING,
    .var=(char_u *)&p_tc,
    .indir=OPT_BOTH(OPT_BUF(BV_TC)),
    .def_val=(char *) "followic",
  },
  [297]={
    .fullname="taglength",
    .shortname="tl",
    .flags=P_NUM,
    .var=(char_u *)&p_tl,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [298]={
    .fullname="tagrelative",
    .shortname="tr",
    .flags=P_BOOL,
    .var=(char_u *)&p_tr,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [299]={
    .fullname="tags",
    .shortname="tag",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NODUP,
    .var=(char_u *)&p_tags,
    .indir=OPT_BOTH(OPT_BUF(BV_TAGS)),
    .def_val=(char *) "./tags;,tags",
  },
  [300]={
    .fullname="tagstack",
    .shortname="tgst",
    .flags=P_BOOL,
    .var=(char_u *)&p_tgst,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [301]={
    .fullname="termbidi",
    .shortname="tbidi",
    .flags=P_BOOL,
    .var=(char_u *)&p_tbidi,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [302]={
    .fullname="termencoding",
    .shortname="tenc",
    .flags=P_STRING,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [303]={
    .fullname="termguicolors",
    .shortname="tgc",
    .flags=P_BOOL|P_UI_OPTION,
    .var=(char_u *)&p_tgc,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [304]={
    .fullname="termpastefilter",
    .shortname="tpf",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_tpf,
    .indir=PV_NONE,
    .def_val=(char *) "BS,HT,ESC,DEL",
  },
  [305]={
    .fullname="terse",
    .flags=P_BOOL,
    .var=(char_u *)&p_force_off,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [306]={
    .fullname="textwidth",
    .shortname="tw",
    .flags=P_NUM|P_RBUF,
    .var=(char_u *)&p_tw,
    .indir=OPT_BUF(BV_TW),
    .def_val=(char *) 0L,
  },
  [307]={
    .fullname="thesaurus",
    .shortname="tsr",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NDNAME|P_NODUP,
    .var=(char_u *)&p_tsr,
    .indir=OPT_BOTH(OPT_BUF(BV_TSR)),
    .def_val=(char *) "",
  },
  [308]={
    .fullname="thesaurusfunc",
    .shortname="tsrfu",
    .flags=P_STRING|P_ALLOCED|P_SECURE|P_FUNC,
    .var=(char_u *)&p_tsrfu,
    .indir=OPT_BOTH(OPT_BUF(BV_TSRFU)),
    .def_val=(char *) "",
  },
  [309]={
    .fullname="tildeop",
    .shortname="top",
    .flags=P_BOOL,
    .var=(char_u *)&p_to,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [310]={
    .fullname="timeout",
    .shortname="to",
    .flags=P_BOOL,
    .var=(char_u *)&p_timeout,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [311]={
    .fullname="timeoutlen",
    .shortname="tm",
    .flags=P_NUM,
    .var=(char_u *)&p_tm,
    .indir=PV_NONE,
    .def_val=(char *) 1000L,
  },
  [312]={
    .fullname="title",
    .flags=P_BOOL,
    .var=(char_u *)&p_title,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [313]={
    .fullname="titlelen",
    .flags=P_NUM,
    .var=(char_u *)&p_titlelen,
    .indir=PV_NONE,
    .def_val=(char *) 85L,
  },
  [314]={
    .fullname="titleold",
    .flags=P_STRING|P_NO_MKRC|P_SECURE,
    .var=(char_u *)&p_titleold,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [315]={
    .fullname="titlestring",
    .flags=P_STRING|P_MLE,
    .var=(char_u *)&p_titlestring,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [316]={
    .fullname="ttimeout",
    .flags=P_BOOL|P_UI_OPTION,
    .var=(char_u *)&p_ttimeout,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [317]={
    .fullname="ttimeoutlen",
    .shortname="ttm",
    .flags=P_NUM|P_UI_OPTION,
    .var=(char_u *)&p_ttm,
    .indir=PV_NONE,
    .def_val=(char *) 50L,
  },
  [318]={
    .fullname="ttyfast",
    .shortname="tf",
    .flags=P_BOOL|P_NO_MKRC,
    .var=(char_u *)&p_force_on,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [319]={
    .fullname="undodir",
    .shortname="udir",
    .flags=P_STRING|P_ONECOMMA|P_EXPAND|P_NO_DEF_EXP|P_SECURE|P_NODUP,
    .var=(char_u *)&p_udir,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [320]={
    .fullname="undofile",
    .shortname="udf",
    .flags=P_BOOL,
    .var=(char_u *)&p_udf,
    .indir=OPT_BUF(BV_UDF),
    .def_val=(char *) false,
  },
  [321]={
    .fullname="undolevels",
    .shortname="ul",
    .flags=P_NUM,
    .var=(char_u *)&p_ul,
    .indir=OPT_BOTH(OPT_BUF(BV_UL)),
    .def_val=(char *) 1000L,
  },
  [322]={
    .fullname="undoreload",
    .shortname="ur",
    .flags=P_NUM,
    .var=(char_u *)&p_ur,
    .indir=PV_NONE,
    .def_val=(char *) 10000L,
  },
  [323]={
    .fullname="updatecount",
    .shortname="uc",
    .flags=P_NUM,
    .var=(char_u *)&p_uc,
    .indir=PV_NONE,
    .def_val=(char *) 200L,
  },
  [324]={
    .fullname="updatetime",
    .shortname="ut",
    .flags=P_NUM,
    .var=(char_u *)&p_ut,
    .indir=PV_NONE,
    .def_val=(char *) 4000L,
  },
  [325]={
    .fullname="varsofttabstop",
    .shortname="vsts",
    .flags=P_STRING|P_COMMA,
    .var=(char_u *)&p_vsts,
    .indir=OPT_BUF(BV_VSTS),
    .def_val=(char *) "",
  },
  [326]={
    .fullname="vartabstop",
    .shortname="vts",
    .flags=P_STRING|P_COMMA|P_RBUF,
    .var=(char_u *)&p_vts,
    .indir=OPT_BUF(BV_VTS),
    .def_val=(char *) "",
  },
  [327]={
    .fullname="verbose",
    .shortname="vbs",
    .flags=P_NUM,
    .var=(char_u *)&p_verbose,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [328]={
    .fullname="verbosefile",
    .shortname="vfile",
    .flags=P_STRING|P_EXPAND|P_SECURE,
    .var=(char_u *)&p_vfile,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [329]={
    .fullname="viewdir",
    .shortname="vdir",
    .flags=P_STRING|P_EXPAND|P_NO_DEF_EXP|P_SECURE,
    .var=(char_u *)&p_vdir,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [330]={
    .fullname="viewoptions",
    .shortname="vop",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_vop,
    .indir=PV_NONE,
    .def_val=(char *) "folds,cursor,curdir",
  },
  [331]={
    .fullname="viminfo",
    .shortname="vi",
    .flags=P_STRING|P_NODEFAULT,
    .indir=PV_NONE,
  },
  [332]={
    .fullname="viminfofile",
    .shortname="vif",
    .flags=P_STRING|P_NODEFAULT,
    .indir=PV_NONE,
  },
  [333]={
    .fullname="virtualedit",
    .shortname="ve",
    .flags=P_STRING|P_ONECOMMA|P_CURSWANT|P_NODUP,
    .var=(char_u *)&p_ve,
    .indir=OPT_BOTH(OPT_WIN(WV_VE)),
    .def_val=(char *) "",
  },
  [334]={
    .fullname="visualbell",
    .shortname="vb",
    .flags=P_BOOL,
    .var=(char_u *)&p_vb,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [335]={
    .fullname="warn",
    .flags=P_BOOL,
    .var=(char_u *)&p_warn,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [336]={
    .fullname="whichwrap",
    .shortname="ww",
    .flags=P_STRING|P_COMMA|P_FLAGLIST,
    .var=(char_u *)&p_ww,
    .indir=PV_NONE,
    .def_val=(char *) "b,s",
  },
  [337]={
    .fullname="wildchar",
    .shortname="wc",
    .flags=P_NUM,
    .var=(char_u *)&p_wc,
    .indir=PV_NONE,
    .def_val=(char *) (intptr_t)TAB,
  },
  [338]={
    .fullname="wildcharm",
    .shortname="wcm",
    .flags=P_NUM,
    .var=(char_u *)&p_wcm,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [339]={
    .fullname="wildignore",
    .shortname="wig",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_wig,
    .indir=PV_NONE,
    .def_val=(char *) "",
  },
  [340]={
    .fullname="wildignorecase",
    .shortname="wic",
    .flags=P_BOOL,
    .var=(char_u *)&p_wic,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [341]={
    .fullname="wildmenu",
    .shortname="wmnu",
    .flags=P_BOOL,
    .var=(char_u *)&p_wmnu,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [342]={
    .fullname="wildmode",
    .shortname="wim",
    .flags=P_STRING|P_ONECOMMA,
    .var=(char_u *)&p_wim,
    .indir=PV_NONE,
    .def_val=(char *) "full",
  },
  [343]={
    .fullname="wildoptions",
    .shortname="wop",
    .flags=P_STRING|P_ONECOMMA|P_NODUP,
    .var=(char_u *)&p_wop,
    .indir=PV_NONE,
    .def_val=(char *) "pum,tagfile",
  },
  [344]={
    .fullname="winaltkeys",
    .shortname="wak",
    .flags=P_STRING,
    .var=(char_u *)&p_wak,
    .indir=PV_NONE,
    .def_val=(char *) "menu",
  },
  [345]={
    .fullname="winbar",
    .shortname="wbr",
    .flags=P_STRING|P_RSTAT|P_ALLOCED|P_MLE,
    .var=(char_u *)&p_wbr,
    .indir=OPT_BOTH(OPT_WIN(WV_WBR)),
    .def_val=(char *) "",
  },
  [346]={
    .fullname="winblend",
    .shortname="winbl",
    .flags=P_NUM|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_WINBL),
    .def_val=(char *) 0L,
  },
  [347]={
    .fullname="winhighlight",
    .shortname="winhl",
    .flags=P_STRING|P_ONECOMMA|P_RWIN|P_ALLOCED|P_NODUP,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_WINHL),
    .def_val=(char *) "",
  },
  [348]={
    .fullname="window",
    .shortname="wi",
    .flags=P_NUM,
    .var=(char_u *)&p_window,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [349]={
    .fullname="winheight",
    .shortname="wh",
    .flags=P_NUM,
    .var=(char_u *)&p_wh,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [350]={
    .fullname="winfixheight",
    .shortname="wfh",
    .flags=P_BOOL|P_RSTAT,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_WFH),
    .def_val=(char *) false,
  },
  [351]={
    .fullname="winfixwidth",
    .shortname="wfw",
    .flags=P_BOOL|P_RSTAT,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_WFW),
    .def_val=(char *) false,
  },
  [352]={
    .fullname="winminheight",
    .shortname="wmh",
    .flags=P_NUM,
    .var=(char_u *)&p_wmh,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [353]={
    .fullname="winminwidth",
    .shortname="wmw",
    .flags=P_NUM,
    .var=(char_u *)&p_wmw,
    .indir=PV_NONE,
    .def_val=(char *) 1L,
  },
  [354]={
    .fullname="winwidth",
    .shortname="wiw",
    .flags=P_NUM,
    .var=(char_u *)&p_wiw,
    .indir=PV_NONE,
    .def_val=(char *) 20L,
  },
  [355]={
    .fullname="wrap",
    .flags=P_BOOL|P_RWIN,
    .var=VAR_WIN,
    .indir=OPT_WIN(WV_WRAP),
    .def_val=(char *) true,
  },
  [356]={
    .fullname="wrapmargin",
    .shortname="wm",
    .flags=P_NUM,
    .var=(char_u *)&p_wm,
    .indir=OPT_BUF(BV_WM),
    .def_val=(char *) 0L,
  },
  [357]={
    .fullname="wrapscan",
    .shortname="ws",
    .flags=P_BOOL,
    .var=(char_u *)&p_ws,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [358]={
    .fullname="write",
    .flags=P_BOOL,
    .var=(char_u *)&p_write,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [359]={
    .fullname="writeany",
    .shortname="wa",
    .flags=P_BOOL,
    .var=(char_u *)&p_wa,
    .indir=PV_NONE,
    .def_val=(char *) false,
  },
  [360]={
    .fullname="writebackup",
    .shortname="wb",
    .flags=P_BOOL,
    .var=(char_u *)&p_wb,
    .indir=PV_NONE,
    .def_val=(char *) true,
  },
  [361]={
    .fullname="writedelay",
    .shortname="wd",
    .flags=P_NUM,
    .var=(char_u *)&p_wd,
    .indir=PV_NONE,
    .def_val=(char *) 0L,
  },
  [362]={.fullname=NULL}
};

#define PV_VTS OPT_BUF(BV_VTS)
#define PV_COM OPT_BUF(BV_COM)
#define PV_TSR OPT_BOTH(OPT_BUF(BV_TSR))
#define PV_FIXEOL OPT_BUF(BV_FIXEOL)
#define PV_FDT OPT_WIN(WV_FDT)
#define PV_CI OPT_BUF(BV_CI)
#define PV_BL OPT_BUF(BV_BL)
#define PV_LIST OPT_WIN(WV_LIST)
#define PV_DEF OPT_BOTH(OPT_BUF(BV_DEF))
#define PV_KMAP OPT_BUF(BV_KMAP)
#define PV_RNU OPT_WIN(WV_RNU)
#define PV_MA OPT_BUF(BV_MA)
#define PV_FEX OPT_BUF(BV_FEX)
#define PV_FDL OPT_WIN(WV_FDL)
#define PV_BT OPT_BUF(BV_BT)
#define PV_STL OPT_BOTH(OPT_WIN(WV_STL))
#define PV_LCS OPT_BOTH(OPT_WIN(WV_LCS))
#define PV_CRBIND OPT_WIN(WV_CRBIND)
#define PV_SW OPT_BUF(BV_SW)
#define PV_FO OPT_BUF(BV_FO)
#define PV_CINSD OPT_BUF(BV_CINSD)
#define PV_BIN OPT_BUF(BV_BIN)
#define PV_DICT OPT_BOTH(OPT_BUF(BV_DICT))
#define PV_SPC OPT_BUF(BV_SPC)
#define PV_LBR OPT_WIN(WV_LBR)
#define PV_RL OPT_WIN(WV_RL)
#define PV_BOMB OPT_BUF(BV_BOMB)
#define PV_DIFF OPT_WIN(WV_DIFF)
#define PV_SUA OPT_BUF(BV_SUA)
#define PV_IMI OPT_BUF(BV_IMI)
#define PV_SBR OPT_BOTH(OPT_WIN(WV_SBR))
#define PV_RLC OPT_WIN(WV_RLC)
#define PV_EFM OPT_BOTH(OPT_BUF(BV_EFM))
#define PV_SWF OPT_BUF(BV_SWF)
#define PV_MENC OPT_BOTH(OPT_BUF(BV_MENC))
#define PV_FML OPT_WIN(WV_FML)
#define PV_IMS OPT_BUF(BV_IMS)
#define PV_BRI OPT_WIN(WV_BRI)
#define PV_LISP OPT_BUF(BV_LISP)
#define PV_WBR OPT_BOTH(OPT_WIN(WV_WBR))
#define PV_MPS OPT_BUF(BV_MPS)
#define PV_CC OPT_WIN(WV_CC)
#define PV_FDN OPT_WIN(WV_FDN)
#define PV_FDC OPT_WIN(WV_FDC)
#define PV_ET OPT_BUF(BV_ET)
#define PV_SMC OPT_BUF(BV_SMC)
#define PV_LOP OPT_BUF(BV_LOP)
#define PV_BRIOPT OPT_WIN(WV_BRIOPT)
#define PV_AI OPT_BUF(BV_AI)
#define PV_INDK OPT_BUF(BV_INDK)
#define PV_INC OPT_BOTH(OPT_BUF(BV_INC))
#define PV_FEN OPT_WIN(WV_FEN)
#define PV_CPT OPT_BUF(BV_CPT)
#define PV_LW OPT_BOTH(OPT_BUF(BV_LW))
#define PV_GP OPT_BOTH(OPT_BUF(BV_GP))
#define PV_AR OPT_BOTH(OPT_BUF(BV_AR))
#define PV_UDF OPT_BUF(BV_UDF)
#define PV_TAGS OPT_BOTH(OPT_BUF(BV_TAGS))
#define PV_INF OPT_BUF(BV_INF)
#define PV_INEX OPT_BUF(BV_INEX)
#define PV_TFU OPT_BUF(BV_TFU)
#define PV_COCU OPT_WIN(WV_COCU)
#define PV_SCBK OPT_BUF(BV_SCBK)
#define PV_SPF OPT_BUF(BV_SPF)
#define PV_UL OPT_BOTH(OPT_BUF(BV_UL))
#define PV_FF OPT_BUF(BV_FF)
#define PV_FDI OPT_WIN(WV_FDI)
#define PV_SISO OPT_BOTH(OPT_WIN(WV_SISO))
#define PV_COLE OPT_WIN(WV_COLE)
#define PV_WINBL OPT_WIN(WV_WINBL)
#define PV_SCBIND OPT_WIN(WV_SCBIND)
#define PV_INDE OPT_BUF(BV_INDE)
#define PV_SPL OPT_BUF(BV_SPL)
#define PV_CHANNEL OPT_BUF(BV_CHANNEL)
#define PV_SCL OPT_WIN(WV_SCL)
#define PV_WM OPT_BUF(BV_WM)
#define PV_EOF OPT_BUF(BV_EOF)
#define PV_WRAP OPT_WIN(WV_WRAP)
#define PV_PVW OPT_WIN(WV_PVW)
#define PV_WFW OPT_WIN(WV_WFW)
#define PV_WINHL OPT_WIN(WV_WINHL)
#define PV_FLP OPT_BUF(BV_FLP)
#define PV_FCS OPT_BOTH(OPT_WIN(WV_FCS))
#define PV_CINO OPT_BUF(BV_CINO)
#define PV_CFU OPT_BUF(BV_CFU)
#define PV_SPELL OPT_WIN(WV_SPELL)
#define PV_QE OPT_BUF(BV_QE)
#define PV_STS OPT_BUF(BV_STS)
#define PV_MOD OPT_BUF(BV_MOD)
#define PV_CUC OPT_WIN(WV_CUC)
#define PV_TS OPT_BUF(BV_TS)
#define PV_FENC OPT_BUF(BV_FENC)
#define PV_EOL OPT_BUF(BV_EOL)
#define PV_NUW OPT_WIN(WV_NUW)
#define PV_NF OPT_BUF(BV_NF)
#define PV_KP OPT_BOTH(OPT_BUF(BV_KP))
#define PV_PI OPT_BUF(BV_PI)
#define PV_CUL OPT_WIN(WV_CUL)
#define PV_ML OPT_BUF(BV_ML)
#define PV_SO OPT_BOTH(OPT_WIN(WV_SO))
#define PV_SYN OPT_BUF(BV_SYN)
#define PV_FP OPT_BOTH(OPT_BUF(BV_FP))
#define PV_MP OPT_BOTH(OPT_BUF(BV_MP))
#define PV_FDE OPT_WIN(WV_FDE)
#define PV_FT OPT_BUF(BV_FT)
#define PV_SI OPT_BUF(BV_SI)
#define PV_FDM OPT_WIN(WV_FDM)
#define PV_RO OPT_BUF(BV_RO)
#define PV_CIN OPT_BUF(BV_CIN)
#define PV_SPO OPT_BUF(BV_SPO)
#define PV_CMS OPT_BUF(BV_CMS)
#define PV_ARAB OPT_WIN(WV_ARAB)
#define PV_VSTS OPT_BUF(BV_VSTS)
#define PV_NU OPT_WIN(WV_NU)
#define PV_ISK OPT_BUF(BV_ISK)
#define PV_BKC OPT_BOTH(OPT_BUF(BV_BKC))
#define PV_PATH OPT_BOTH(OPT_BUF(BV_PATH))
#define PV_WFH OPT_WIN(WV_WFH)
#define PV_CSL OPT_BUF(BV_CSL)
#define PV_TC OPT_BOTH(OPT_BUF(BV_TC))
#define PV_CINW OPT_BUF(BV_CINW)
#define PV_SCROLL OPT_WIN(WV_SCROLL)
#define PV_VE OPT_BOTH(OPT_WIN(WV_VE))
#define PV_FMR OPT_WIN(WV_FMR)
#define PV_CULOPT OPT_WIN(WV_CULOPT)
#define PV_EP OPT_BOTH(OPT_BUF(BV_EP))
#define PV_CINK OPT_BUF(BV_CINK)
#define PV_OFU OPT_BUF(BV_OFU)
#define PV_BH OPT_BUF(BV_BH)
#define PV_TW OPT_BUF(BV_TW)
#define PV_TSRFU OPT_BOTH(OPT_BUF(BV_TSRFU))
