#!/bin/sh
set -e

cmake -S Third-Party/neovim -B .build -DCMAKE_BUILD_TYPE=Release
cmake --build .build/ --target package

rm -rf .build/nvim-macos/
tar -C .build/ -xvf .build/nvim-macos-arm64.tar.gz
