#!/usr/bin/env zsh
set -e

() {
  cmake -S Third-Party/neovim \
    -B .build/neovim \
    -G 'Unix Makefiles' \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
    -DCMAKE_OSX_ARCHITECTURES=arm64

  cd .build/neovim
  make package

  tar -xvf nvim-macos-arm64.tar.gz
  rm -rf ../package
  mv nvim-macos-arm64 ../package
}
