#!/usr/bin/env zsh

set -

cd "${0:a:h}/../Third-Party/neovim/.deps"

rm -rf ./Cmsgpack.xcframework

xcodebuild -create-xcframework -library ./usr/lib/libmsgpack-c.a -headers ./usr/include -output  ./Cmsgpack.xcframework

# -library ./usr/lib/libunibilium.a \
# -library ./usr/lib/liblpeg.a \
# -library ./usr/lib/libluajit-5.1.a \
# -library ./usr/lib/libuv.a \
# -library ./usr/lib/libtree-sitter.a \
