#!/bin/sh

if [ -z "$1" ]; then
  >&2 echo "Usage: $0 project_root"
  exit 1
fi

NVIM_PATH="$1/.build/bin/nvim"
GENERATE_CMD="swift run --package-path $1/Modules generate"

GENERATED_DIR="$1/Modules/Sources/Neovim/generated"
${NVIM_PATH} --api-info | eval "${GENERATE_CMD} ${GENERATED_DIR}"

"$1/Third-Party/swift-format/swift-format" format -i --configuration "$1/swift-format.json" -r -p "${GENERATED_DIR}"
